config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 get 'welcome/index'
 get 'welcome/about'


 resources :registered_applications do
   resources :events
end

 namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]


end

 root to: 'welcome#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application

  validates :registered_application, presence: true
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy

validates :user, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
has_many :registered_applications


  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
    skip_before_action :verify_authenticity_token
    skip_before_action :authenticate_user!
    before_filter :set_access_control_headers

    def set_access_control_headers
        headers['Access-Control-Allow-Origin'] = '*'
        headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
        headers['Access-Control-Allow-Headers'] = 'Content-Type'
    end

    def preflight
        head 200
    end


    def index
    if request.method == "OPTIONS"
     render :json => '', :content_type => 'application/json'
     return
    end
   end

   def create
    registered_application = RegisteredApplication.where(url: request.env['HTTP_ORIGIN']).try(:first)
    if registered_application.nil?
      render json: "Unregistered application", status: :unprocessable_entity
    else
      @event = registered_application.events.new(event_params)
      if @event.save
        render json: @event, status: :created
      else
        render json: @event.errors, status: :unprocessable_entity
      end
    end
  end

   private

   def event_params
     params.permit(:name)
   end

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
      before_action :authenticate_user!
      protect_from_forgery with: :exception

      private

      def require_sign_in
          unless current_user
              flash[:alert] = 'You must be logged in to do that'
              redirect_to new_session_path
          end
      end
  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    @registered_application = RegisteredApplication.find(params[:registered_application_id])
    @event = @registered_application.event.new(event_params)

    if @event.save
      flash[:notice] = "Event saved successfully."
      redirect_to @registered_application
    else
      flash[:alert] = "There was an error saving the event."
      redirect_to @registered_application
    end
  end

  def show
    @registered_application = RegisteredApplication.find(current_user)
    @events = @registered_application.events.new(event_params)
    <a id="post1" onclick="blocmetrics.report(this.id);" href="/path/to/post">Post 1</a>
  end

  private

  def event_params
    params.permit(:name)
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController

  def new
    @registered_application = RegisteredApplication.new
  end

  def index
    @registered_applications = current_user.registered_applications
    @event = Event.all
  end

  def show
    @app = RegisteredApplication.includes(:events).where(id: params[:id]).first
    @registered_application = current_user.registered_applications
    @events = Event.all
end

  def create
    @registered_application = RegisteredApplication.new(:registered_application_id)
      respond_to do |format|
        if @registered_application.save
          format.html { redirect_to @registered_application, notice: 'Registered application was successfully created.' }
          format.json { render :show, status: :created, location: @registered_application }
        else
          format.html { render :new }
          format.json { render json: @registered_application.errors, status: :unprocessable_entity }
        end
      end
    end

  def edit
   @registered_application = RegisteredApplication.find(current_user)
  end

  def destroy
    @registered_application = RegisteredApplication.find(current_user)
     @registered_application.destroy
      flash[:notice] = "#{@registered_application.name} was unregistered successfully."
      redirect_to registered_application_path
  end



  def update
      @registered_application = RegisteredApplication.find(current_user)
      @registered_application.name = params[:registered_application][:name]
      @registered_application.url = params[:registered_application][:url]

      respond_to do |format|
      if @registered_application.update(application_params)
        format.html { redirect_to @registered_application, notice: 'Registered application was successfully updated.' }
        format.json { render :show, status: :ok, location: @registered_application }
      else
        format.html { render :edit }
        format.json { render json: @registered_application.errors, status: :unprocessable_entity }
      end
    end
  end


  private


    def application_params
      params.require(:registered_application).permit(:name, :url)
    end

    def event_params
      params.permit(:name)
    end

    def user_log_in?
      redirect_to user_session_path unless user_signed_in?
    end
   end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:user_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
              <ul class="nav nav-tabs">
                  <li><%= link_to "Blocmetrics", root_path %></li>
                  <li><%= link_to "URLs", registered_applications_path %></li>
                  <% if current_user %>
                  <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
              <% else %>
                  <li><%= link_to('Login', new_user_session_path)  %></li>
                  <li><%= link_to('Register now!', new_user_registration_path)  %></li>
                  <% end %>
              </ul>
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
              <%= yield %>
          </div>
</body>
</html>

app/views/registered_applications/_app.html.erb
<%= fields_for (@registered_applications) do |app| %>
<table class="table table-striped">
<tr>
  <td><%= link_to 'Name', registered_application_path(app) %></td>
  <td><%= link_to 'URL' %></td>
  <td><%= link_to 'Show', registered_application_path(app) %></td>
  <td><%= link_to 'Edit', edit_registered_application_path(app) %></td>
  <td><%= link_to 'Delete', registered_application_path(app), method: :destroy, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
</table>

app/views/registered_applications/_form.html.erb
<%= form_for (@registered_application) do |f| %>
<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter app name", autofocus: true %>
</div>
<div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Enter app url" %>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/registered_applications/edit.html.erb
<h1>Edit Your Registered App</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @registered_application, url: registered_application_path(@registered_application.user_id, @registered_application.id) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter the site's name here" %>
      </div>
      <div class="form-group">
        <%= f.label :URL %>
        <%= f.text_field :url, class: 'form-control', placeholder: "Enter the site's URL here" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="5"><h1 text-align="center">Registered Applications</h1></th>
    </tr>
    <tr>
      <%= render partial: 'app' %>
    </tr>
  </thead>
  <tfoot>
    <th colspan="5" align="center"><%= link_to 'Register A New Application', new_registered_application_path, class: 'btn btn-lg btn-success center-block' %></th>
  </tfoot>
</table>

app/views/registered_applications/new.html.erb
<h1>New Application</h1>
<div class="row">
  <div class="col-md-12">
    <p>Your new application will be available for tracking upon successful registration.</p>
  </div>
</div>

<div class="col-md-8">
  <%= render partial: 'form' %>
  <%= link_to 'Back To Applications', registered_applications_path %>
</div>

app/views/registered_applications/show.html.erb
<h1><%= @registered_application.name %></h1>

<div class="row">
  <div class="col-md-8">

    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= pie_chart @registered_application.group(:name).count %>
    <%= line_chart @registered_application.group_by_day(:created_at).count %>


      <p style="font-size:14px;"><%= @events.count %> events created</p>
      <p style="font-size:12px;">Added by <%= @registered_application.try(:email) %></p>

  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_registered_application_path, class: 'btn btn-success' %>
    <%= link_to "Delete", registered_application_path(current_user.id, @registered_application), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this app from Blocmetrics?'} %>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
 <% end %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Hello, <%= current_user.email %>!</h1>
 <% if user_signed_in? %>
   Logged in as <strong><%= current_user.email %></strong>.
   <%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %> |
   <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %>
   <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
   <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>